local:
	g++ -std=c++11 reciever.cpp
	./a.out madlab-ubuntu 6049
homeReciever:
	g++ -std=c++11 reciever.cpp
	./a.out vm-02.cs.siue.edu 6049
osReciever:
	g++ -std=c++11 reciever.cpp
	./a.out vm-10.cs.siue.edu 6049
