local:
	g++ -g -std=c++11 sender.cpp
	./a.out madlab-ubuntu 6050
homeClient:
	g++ -g -std=c++11 sender.cpp
	./a.out vm-02.cs.siue.edu 6050
osClient:
	g++ -g -std=c++11 sender.cpp
	./a.out vm-10.cs.siue.edu 6050
